config/routes.rb
Rails.application.routes.draw do
  resources :categories
  get 'users/edit'
  resources :users, only: [:update]
  get "perfil", to:"users#edit"
  resources :photos
  get 'my_photos',        to: 'photos#my_photos', as: 'my_photos'
  devise_for :users
  get 'home/index'
  resources :articles
  resources :comments
  get 'bienvenida', to:"home#index"
  root to: "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/article.rb
  class Article < ApplicationRecord
    has_rich_text :content
    belongs_to :user
    has_many :comments
    has_many :has_categories
    has_many :categories, through: :has_categories
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: [:new, :destroy]
  # GET /articles or /articles.json
  def index
    @articles = Article.order("title DESC")
    @articles = Article.paginate(:page=>params[:page],per_page:3).order("created_at desc")
    if params[:title].present?
      @articles = @articles.where("title ILIKE ?", "%#{params[:title]}%")
    elsif params[:title] == params[:title].nil?
      flash[:notice] = "No hay coincidencias"
    end
    if params[:title].present?
      @articles = @articles.where("title ILIKE ?", "%#{params[:title]}%")

    elsif params[:title] == params[:title].nil?
      flash[:notice] = "No hay coincidencias"
    end
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)
    @article.user = current_user
    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :content, :user_id)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_comments.html.erb
<div class="card comments mt-5 mb-5">
  <div class="card-header border-bottom-0 font-weight-bold bg-transparent">Comentarios</div>
  <ul class="list-group list-group-flush">
    <% @article.comments.each do |comment| %>
      <li class="list-group-item">
        <header class="comment-header"><strong><%= comment.user.email %></strong> wrote <%= distance_of_time_in_words(Time.current, comment.created_at) %> ago</header>
        <div class="comment-body"><%= comment.body %></div>
      </li>
    <% end %>

    <% if @article.comments.empty? %>
      <li class="list-group-item text-center">Aún no hay comentarios para este artículo :(</li>
    <% end %>
  </ul>
</div>

<% if signed_in? %>
  <div class="card bg-light new-comment">
    <div class="card-body">
      <p class="font-weight-bold">Deja tu comentario:</p>
      <%= form_for @article.comments.build do |f| %>
        <%= f.hidden_field :article_id, value: @article.id %>
        <div class="form-group">
          <%= f.text_area :body, rows: 4, class: "form-control" %>
        </div>

        <div class="text-right">
          <%= f.submit "Comentar", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
<% else %>
  <div class="card bg-light mt-5">
    <div class="card-body">
      <p class="card-text text-center lead"><%= link_to "Regístrate", new_user_registration_path %> o <%= link_to "Ingresa", new_user_session_path %> para comentar</p>
    </div>
  </div>
<% end %>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

 <div class="field">
    <%= form.label :content %>
    <%= form.rich_text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<div class="container">
<%= form_tag articles_path, method: :get do %>
    <div class="row">
      <div class="form-group col-4 col-md-4">
        <%= text_field_tag :title, params[:title], class: "form-control", placeholder: "¿qué estás buscando?" %>
      </div>
      <div class="form-group col-6 col-md-4">
          <%= submit_tag "Buscar", name: nil, class: "btn btn-primary btn-md" %>
      </div>

    <% end %>  
    </div>
<p id="notice"><%= notice %></p>

<h1>Articulos</h1>

<div class="row row-cols-3">
    <% @articles.each do |article| %>
    <div class="col">
      <div class="card border-primary mb-3" style="max-width: 18rem;">

            <div class="card-header"><%= article.title %></div>
            <div class="card-body text-secondary"><%= article.created_at %></div>
            <div class="card-body text-primary"><%= link_to 'Ver más', article %></div>
            <div class="card-footer bg-transparent border-primary">Autor: <%= article.user.email %></div>

      </div>
    </div>
    <% end %>

<br>

<%#= link_to 'New Article', new_article_path %>
</div>
<div class="pagination" style="font-size: small">
<%= 
will_paginate @articles,
  :class          => 'pagination',
  :previous_label => ' &laquo; Anterior ',
  :next_label     => ' Siguiente &raquo; ',
  :inner_window   => 4, # links around the current page
  :outer_window   => 1, # links around beginning and end
  :separator      => ' - ', # single space is friendly to spiders and non-graphic browsers
  :param_name     => :page,
  :params         => nil,
  
  :page_links     => true,
  :container      => true

%>
</div>
</div>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <h1 class="text-uppercase"><%= @article.title %></h1>
</p>
<p><<%= @article.user.email %>/p>
<p>
  <%= @article.content %>
</p>

<% if signed_in? %>
    <% if current_user.email == @article.user.email %>
      <%= link_to "Eliminar", @article, method: :delete, class: "btn btn-danger btn-sm" %> |
    <% end %>
    <% if current_user.email == @article.user.email %>
      <%= link_to "Editar", edit_article_path(@article), class: "btn btn-primary btn-sm" %>
    <% end %>
  <% end %>

<%= render "comments" %>

<hr>
<div class="">
	<p class="label"><strong>Tags:</strong>
	<% @article.categories.each do |category| %>
		<span class="badge badge-pill padding rounded-pill" style="background-color:<%=category.color %>; text-decoration: none;">
			<%= link_to category.title, category, class:"tag" %>
		</span>

	<% end %>
	</p>
</div>