config/routes.rb
Rails.application.routes.draw do
  resources :categories
  get 'users/edit'
  resources :users, only: [:update]
  get "perfil", to:"users#edit"
  resources :photos
  get 'my_photos',        to: 'photos#my_photos', as: 'my_photos'
  devise_for :users
  get 'home/index'
  resources :articles
  resources :comments
  get 'bienvenida', to:"home#index"
  root to: "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/photo.rb
class Photo < ApplicationRecord
  enum license: [:copyright, :copyleft, :creative_comons]
  enum visibility:[:pub, :priv]
  belongs_to :user
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  skip_before_action :verify_authenticity_token, only: :new_session

  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  #para este he creado un nuevo formulario en layouts/photos
  #incluir el archivo del controlador photos_helper
  include PhotosHelper

  def index

    @photos = get_possible_photos

  end
  def new
    @photo = Photo.new
  end

  def my_photos
    @photos = current_user.photos
  end

  def create
    @photo = Photo.create(photo_params)
    @photo.user = current_user
    if @photo.save
      redirect_to photo_path(@photo), notice: 'Foto creada correctamente'
    else
      flash[:alert] = 'Error al querer guardar la foto '+ @photo.errors.full_messages.to_sentence
      render :new
    end
  end

  def show
    @possible_photos = get_possible_photos

    #le digo que mi foto viene como parametro por id
    @photo = @possible_photos.find_by_id(params[:id])
    if @photo.nil?
      #pintar la pagina co error 404
      render file: "#{Rails.root}/public/404.html", status: :not_found #404
    else
      render :show
    end
  end

  def edit
    @photo = current_user.photos.find_by_id(params[:id])
    if @photo.nil?
      render file: "#{Rails.root}/public/404.html", status: :not_found #404
    else
      render :edit
    end
  end

  def update
    @photo = current_user.photos.find_by_id(params[:id])
    if @photo.nil?
      render file: "#{Rails.root}/public/404.html", status: :not_found #404
    elsif @photo.update(photo_params)
      flash[:notice] = 'La foto '+ @photo.name + ' se ha actualizado correctamente'
      redirect_to photo_path(@photo)
    else
      flash[:alert] = 'Ocurrió un error al querer actualizar la foto'
      render :edit
    end
  end

  def destroy
    @photo = current_user.photos.find_by_id(params[:id])
    @photo.destroy
    flash[:notice] = 'La foto '+@photo.name+' ha sido eliminada correctamente'
    redirect_to :my_photos
  end


  private
  def photo_params
    params.require(:photo).permit(:name, :url, :description, :license, :visibility, :user_id)
  end

end

app/helpers/photos_helper.rb
module PhotosHelper
# si se cumple, el usuario autenticado podrá ver sus fotos o las fotos públicas
# si no se cumple, el usuario no autenticado verá solamente las fotos públicas
	def get_possible_photos
		if current_user
	  		@possible_photos = Photo.where(user: current_user).or(Photo.where(visibility: :pub))
	  	else
	  		@possible_photos = Photo.where(visibility: :pub)
	  	end
	  	return @possible_photos
	end
end

app/views/photos/_photo_form.html.erb
<%= form_for @photo do |f| %>

  <%= f.label :name, 'Titulo' %>
  <%= f.text_field :name, required: true %>
  <br><br>

  <%= f.label :url, 'URL' %>
  <%= f.text_field :url, required: true %>
  <br><br>

  <%= f.label :description, 'Descripcion' %>
  <%= f.text_area :description %>
  <br><br>

  <%= f.label :visibility, 'Visibilidad'%>
  <!-- Photo::visibilities.keys.to_a //toma las claves y lo convierte en un array -->
  <%= f.select :visibility, Photo::visibilities.keys.to_a, required: true %>

  <%= f.label :license, 'Licencia' %>
  <%= f.select :license, Photo::licenses.keys.to_a, required: true %>
  <br><br>

  <% if @photo.new_record? %>
    <%= f.submit 'Crear foto' %>
  <% else %>
    <%= f.submit 'Actualizar foto' %>
  <% end %>
<% end %>

app/views/photos/_photos_loop.html.erb
<% @photos.each do |photo| %>
	<%= link_to photo_path(photo) do %>
		<img src="<%= photo.url %>" alt="<%= photo.name %>" height="150" class="img-rounded">
	<% end %>
<% end %>

app/views/photos/edit.html.erb
<img src="<%= @photo.url %>" alt="<%= @photo.name %>" height="300">

<%= render partial: 'photo_form', object: @photo %>

app/views/photos/index.html.erb
<h1>Bienvenido a esta página</h1>
<p>Este es un blog para publicar imágenes</p>

<% if @photos.any? %>
<!-- si se va cargar todo, usar @photos.find_each-->
	<h2>Últimas fotos publicadas</h2>

	<%= render partial: "photos_loop", object: @photos %>


<% else %>
	<p>Sé el primero en publicar una foto.</p>
<% end %>

app/views/photos/my_photos.html.erb
<h1>Mis fotos</h1>

<%= render partial: "photos_loop", object: @photos %>

app/views/photos/new.html.erb
<%= render partial: 'photo_form' %>

app/views/photos/show.html.erb
<% content_for :title do %>
<%= @photo.name %>
<% end %>
<!-- aqui se muestra todo el detalle de las fotos -->
<h1><%= @photo.name %> </h1>
<img src=<%= @photo.url %> alt=<%= @photo.name %> height="300">

<h2>Description:</h2>
<p><%= @photo.description %></p>

<h2>Author:</h2>
<p> <%= @photo.user.email %></p>

<br><br>

<% if @photo.user == current_user %>
  <%= link_to 'Editar', edit_photo_path %>
  <%= link_to 'Borrar', photo_path, method: :delete, data: {confirm: '¿Estás seguro?'} %>
<% end %>